server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DBHOST}.postgres.database.azure.com:5432/${DBNAME}?sslmode=require
    username: ${DBUSER}
    password: ${DBPASS}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://lemur-18.cloud-iam.com/realms/giftbuddy
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
  logging:
    level:
      org:
        springframework: DEBUG