version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres-keycloak:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command:
      - start-dev
      - --import-realm
    env_file:
      - .env.keycloak
    ports:
      - "9999:8080"
    depends_on:
      - postgres-keycloak
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json