version: '3.8'

volumes:
  postgres-data:
    name: postgres-giftbuddy-data
    driver: local

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env.database
    ports:
      - 5432:5432
    networks:
        - giftbuddy-network
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  giftbuddy-network:
    name: giftbuddy-network

